<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace>DotVVM.Benchmarks</RootNamespace>
    <AssemblyName>DotVVM.Benchmarks</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources/*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\dotvvm\src\Framework\Hosting.AspNetCore\DotVVM.Framework.Hosting.AspNetCore.csproj" />
    <ProjectReference Include="..\dotvvm\src\Samples\AspNetCoreLatest\DotVVM.Samples.BasicSamples.AspNetCoreLatest.csproj" />
    <ProjectReference Include="..\dotvvm\src\Framework\Testing\DotVVM.Framework.Testing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="0.16.0" />
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="MedallionShell" Version="1.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="3.1.19" />
  </ItemGroup>
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);$(AdditionalBenchmarkConstants)</DefineConstants>
  </PropertyGroup>
</Project>
